### ISSUE TITLE
Слайдер

### ISSUE THREAD

**Issue by foxhable** [aaccent/uveda_layout#1]
**Страница:** Главная

**Проблема:**
Последний элемент не полностью влезает и слегка обрезается
<details><summary>Фото</summary>

![{AF47476D-78F2-40E6-AB84-1BB5F3A7507A}](https://github.com/user-attachments/assets/99f8501d-a87a-4983-9d6c-256410a9fe6d)
</details>

**Comment by RamizAshurov** [comment]
![image](https://github.com/user-attachments/assets/dfccee77-1a29-46e3-b5a5-6a2af203b276)
У меня вроде влезает. Видимо, скроллбар "съедает" ширину контейнера

**Comment by foxhable** [comment]
Да, у тебя влезает потому что нет полосы прокрутки. Конечный пользователь будет с полосой прокрутки, а значит у него всегда будет обрезаться. Давай `slidesPerView` в свайпере выставим не `"auto"`, а конкретные значения, чтобы свайпер выставлял ширину слайдов.

**Comment by RamizAshurov** [comment]
Исправил
