### ISSUE TITLE
Мобильное меню

### ISSUE THREAD

**Issue by foxhable** [aaccent/uveda_layout#10]
**Страница:** Все

**Проблема:**
Нужно сделать чтобы в мобилке при нажатии на "Каталог" не происходил переход на страницу каталога. Иначе пользователи вечно будут кликать не туда
<details><summary>Скрин</summary>

![image](https://github.com/user-attachments/assets/13c390ca-6cdd-4dd3-825a-39fd0905081b)
</details>

**Comment by RamizAshurov** [comment]
Исправил

**Comment by foxhable** [comment]
Но при этом должно раскрываться меню каталога, сейчас оно раскрывается только по нажатию на стрелку

**Comment by RamizAshurov** [comment]
Сделал
