### ISSUE TITLE
Ссылки на категории

### ISSUE THREAD

**Issue by foxhable** [aaccent/uveda_layout#11]
**Страница:** Каталог

**Проблема:**
Элементы с ссылками на категории в макете меньше высоты
<details><summary>Скрин</summary>

![image](https://github.com/user-attachments/assets/de86ff9c-dac9-4578-b6aa-ec9d1a28f8db)
</details>

**Comment by RamizAshurov** [comment]
![image](https://github.com/user-attachments/assets/6a259963-12cd-4e64-bb7a-94877b8cc326)
В макете ширина экрана 380, а на скрине 390.
На мобилке ширина карточки зависит от ширины экрана, и высота соотвественно тоже, так как у картчоки стоит aspect-ratio

**Comment by foxhable** [comment]
Вот на `380px`, проверял на Edge и Chrome
<details><summary>Скрин</summary>

![image](https://github.com/user-attachments/assets/4c21759e-d043-4e2d-9cd7-ae75e8c6dd43)
</details>

**Comment by RamizAshurov** [comment]
У меня все норм. И в edge  и в chrome
Это же страница каталога?

**Comment by regina-ms** [comment]
Ты наверно в dev режиме смотришь, там действительно все ок. Глянь по ссылке https://aaccent.github.io/uveda_layout/catalog.html
