### ISSUE TITLE
Попап фильтра

### ISSUE THREAD

**Issue by foxhable** [aaccent/uveda_layout#13]
**Страница:** Категория, Подкатегория (products.html) и Акции

**Проблема:**
1. В мобильной версии не открывается попап фильтра при нажатии на "Фильтрация по продукции"
<details><summary>Скрин</summary>

![{C8E27862-4E2B-4DB6-AD86-36EE642C3B0A}](https://github.com/user-attachments/assets/9b3bccd0-29e4-4ff3-a886-ef2a3073ac8f)
</details> 

2. Нужно сделать кнопку тэгом `button`

**Comment by RamizAshurov** [comment]
Исправил

**Comment by foxhable** [comment]
Не, кнопкой нужно сделать весь `.sidebar__header`

**Comment by RamizAshurov** [comment]
Сделано
