### ISSUE TITLE
Карта

### ISSUE THREAD

**Issue by foxhable** [aaccent/uveda_layout#14]
**Страница:** Контакты

**Проблема:**
1. Нельзя перемещать карту мышкой и пальцами
2. Иконка метки стандартная от яндекса. В макете изображена кастомизированная
3. В требованиях было указано, что было заложена возможность выводить несколько меток и данные должны парситься через скрытый элемент в DOM структуре. Должна быть возможность выводить несколько меток и при нажатии на них меняется информация в карточке
4. Иконки соц сетей с темным фоном, в макете они светлого
<details><summary>Скрин</summary>

![{E75554DB-9996-4701-A2D5-06BF257C2046}](https://github.com/user-attachments/assets/82f1f98e-8e7f-4389-bc03-7db59b26f4da)
</details>

**Comment by RamizAshurov** [comment]
1. Исправил
2. Исправил
3. Координаты метки берутся из data атрибутов. Если таких нет, то в js стоят значения по умолчанию. Data атрибуты я добавил. Про возможность выводить несколько меток и менять содержимое карточки по клику по ним в требованиях не было указано
![image](https://github.com/user-attachments/assets/7d2d9bd3-97aa-4cac-8c51-0cd8183ee5a7)

**Comment by foxhable** [comment]
3. Это требование ниже под заголовком "Контакты" в пункте 1. Если ты его видел и не понял, то хер с ним - мой косяк, надо было понятнее писать. Это в любом случае моя инициатива и необязательно
![image](https://github.com/user-attachments/assets/45a413e4-a80a-49de-b0e3-de24c8772884)
