### ISSUE TITLE
Длинные хлебные крошки

### ISSUE THREAD

**Issue by foxhable** [aaccent/uveda_layout#16]
**Страница:** Подкатегория (products.html)

**Проблема:**
Длинные хлебные крошки заходят за экран
<details><summary>Скрин</summary>

![image](https://github.com/user-attachments/assets/a4b74207-9e1b-41fe-af8b-31feba7374e5)
</details>

**Comment by RamizAshurov** [comment]
Исправил

**Comment by foxhable** [comment]
Нужно ещё отступ справа добавить, чтобы не прибит к краю был
![image](https://github.com/user-attachments/assets/f1920a95-3ef0-4cbe-90e2-775270c54c10)

**Comment by RamizAshurov** [comment]
Исправил
