### ISSUE TITLE
Оставить заявку в продукте

### ISSUE THREAD

**Issue by foxhable** [aaccent/uveda_layout#18]
**Страница:** Детальная продукта

**Проблема:**
Кнопка "Оставить заявку" ничего не делает при нажатии, должна открывать попап звонка
<details><summary>Скрин</summary>

![{7F63A68A-F54F-4B2C-B234-6F9E14EE89C1}](https://github.com/user-attachments/assets/28a3a859-1a72-412a-b14a-dfe6fc280814)
</details>

**Comment by foxhable** [comment]
Возможно это из-за ошибки
![{46242C44-2311-446F-A1D3-8541CBF9BCAE}](https://github.com/user-attachments/assets/4e51780b-b2fc-4523-a598-306baebdc0ac)

**Comment by RamizAshurov** [comment]
Исправил
