### ISSUE TITLE
Миниатюры слайдера продукта

### ISSUE THREAD

**Issue by foxhable** [aaccent/uveda_layout#19]
**Страница:** Детальная продукта

**Проблема:**
При нажатии на миниатюры фотографий в слайдере продукта должны переключаться фотографии
<details><summary>Скрин</summary>

![{FF17A10A-1668-41C1-BB25-E0AFDF6D33E5}](https://github.com/user-attachments/assets/7b0668fe-40aa-40bf-85ef-2c4c6d239215)
</details>

**Comment by foxhable** [comment]
Возможно это из-за ошибки
![{46242C44-2311-446F-A1D3-8541CBF9BCAE}](https://github.com/user-attachments/assets/4e51780b-b2fc-4523-a598-306baebdc0ac)

**Comment by RamizAshurov** [comment]
Исправил
