### ISSUE TITLE
Скрытие фильтров

### ISSUE THREAD

**Issue by foxhable** [aaccent/uveda_layout#21]
**Страница:** Акции

**Проблема:**
Категории фильтров должны быть скрыты и при нажатии на кнопку должны раскрываться
<details><summary>Скрин</summary>

![image](https://github.com/user-attachments/assets/b265c3f2-8257-4d5f-bce9-9011b8024c78)
</details>

**Comment by RamizAshurov** [comment]
Проверил, вроде все работает.
Для наглядности добавил cursor: pointer при наведении + смену цвета

**Comment by foxhable** [comment]
Работает на странице Акции? В каталоге оно работает, на Акциях нет.
<details><summary>Скрин</summary>

![image](https://github.com/user-attachments/assets/4e7d63da-c590-47b8-b960-e588aefc9998)
</details>

**Comment by RamizAshurov** [comment]
Проглядел Акции. Теперь работает
