### ISSUE TITLE
Большие заголовки

### ISSUE THREAD

**Issue by foxhable** [aaccent/uveda_layout#4]
**Страница:** Главная

**Проблема:**
Большие декоративные заголовки выходят за контейнер. Это скорее всего из-за полосы прокрутки. Давай уменьшим размер шрифта чтобы он влезал в контейнер

<details><summary>Скрин1</summary>

![image](https://github.com/user-attachments/assets/f061bdbb-5a16-4067-b36f-13e4aaa324c7)
</details> 

<details><summary>Скрин2</summary>

![image](https://github.com/user-attachments/assets/e1748b64-bb17-4d78-b433-3c55089300d6)
</details>

**Comment by RamizAshurov** [comment]
Исправил
