### ISSUE TITLE
Попап обрезается

### ISSUE THREAD

**Issue by foxhable** [aaccent/uveda_layout#5]
**Страница:** Все

**Проблема:**
Попап по высоте обрезается на ноутбучных разрешениях
<details><summary>Скрин десктопа</summary>

![image](https://github.com/user-attachments/assets/cf386bd4-6ed3-4c06-8988-1af106335dd9)
</details> 

<details><summary>Скрин мобилки</summary>
![{FF506F06-78A2-4A4A-A571-BF3EFA30DD35}](https://github.com/user-attachments/assets/fc6400c8-49e2-4e4f-8bb8-d3d080173929)
</details>

**Comment by RamizAshurov** [comment]
Исправил

**Comment by foxhable** [comment]
Можешь ещё сделать, чтобы для разрешений `1280px`, `1366px` и `1400px` не появлялась полоса прокрутки путем уменьшения внутренних отступов, высоты полей и размера заголовка
