### ISSUE TITLE
Попап звонка

### ISSUE THREAD

**Issue by foxhable** [aaccent/uveda_layout#6]
**Страница:** Все

**Проблема:**
1. В полях у попап звонка белый текст
  <details><summary>Скрин</summary>
  
  ![image](https://github.com/user-attachments/assets/9193dde7-dba4-4a9c-8154-a3d34a0b3bc5)
  </details> 
2. У кнопки "Оставить заявку" стрелка пропала
  <details><summary>Скрин</summary>
  
  ![{73965289-6B10-4956-A7EA-75BD9F5B9F43}](https://github.com/user-attachments/assets/6599329d-c1ab-4823-9858-4116659c745f)
  </details>

**Comment by RamizAshurov** [comment]
1. Исправил
2. Исправил
