### ISSUE TITLE
Тэги заголовков

### ISSUE THREAD

**Issue by foxhable** [aaccent/uveda_layout#7]
**Страница:** Главная

**Проблема:**
Нужно расставить тэги:
- Заголовок блока "Актуальные акции" сделать `h2`
  <details><summary>Скрин</summary>
  
  ![image](https://github.com/user-attachments/assets/d4b53a65-5ff1-4fa7-a8ad-42c994284290)
  </details> 
- У блока "Продукция" сделать `h2`
  <details><summary>Скрин</summary>
  
  ![{26F7D345-F4D0-433F-992B-8A76DA376B90}](https://github.com/user-attachments/assets/6399d91c-1e7e-48a5-90ac-f39990746866)
  </details> 
- У блока с формой сделать `h2`
  <details><summary>Скрин</summary>
  
  ![{DFFDBE3C-55C1-4442-A7B5-EC1E540A44B7}](https://github.com/user-attachments/assets/ce6bf3f3-e266-43e1-8fb4-763806541c9a)
  </details> 
- У блока "Почему нам ~не~ стоит доверять" `h2`
  <details><summary>Скрин</summary>
  
  ![{CD72D5B8-B505-48A2-8F4B-F7E9C65C5C24}](https://github.com/user-attachments/assets/d49b7ed5-e642-41b3-bfcf-eafaaecee87f)
  </details> 
- У блока "Нам доверяют" `h2`
  <details><summary>Скрин</summary>
  
  ![{2F7A6FA4-C2CC-472B-87CF-D7B3A675CA50}](https://github.com/user-attachments/assets/0983cb71-7f9a-4e6e-a4ef-a91c7a4424a3)
  </details> 
- У блока "Обратная связь" `h2`
  <details><summary>Скрин</summary>
  
  ![{5A51846A-026A-432A-8A30-1063DF007451}](https://github.com/user-attachments/assets/d9595b4d-8107-4010-b750-fec5d23f078a)
  </details>

**Comment by RamizAshurov** [comment]
Исправил

**Comment by foxhable** [comment]
Я в блоке "О компании" пропустил ещё - там тоже `h2`
<details><summary>Скрин</summary>

![image](https://github.com/user-attachments/assets/1f7d8850-65b2-4730-984b-74a62842d5eb)
</details>

**Comment by RamizAshurov** [comment]
Исправил
